library(stringr)
library(tidyverse)
source("r formatted data/r_aug13_TempehTemplate-SelectedDataAug8Prol_R_2024-08-13_1139.r")

colnames(data)

# COLUMN SEARCHER
tidyr::tibble(cols=colnames(data))  %>% dplyr::filter(stringr::str_detect(cols, "start"))

# STRING PRINTER
cat(shQuote(levels(data_clean$block_order)), sep='\n')

# Check, that there's exactly one outcome measure response in each row; Should
# return TRUE
all(rowSums(is.na(data_clean[c("protein_1.factor", "protein_2.factor", "protein_3.factor")])) == 2)
#


data_clean = data %>%
  # Filter out consent form signature events
  dplyr::filter(!stringr::str_detect(redcap_event_name, "^consent")) %>%

  # Since RedCap randomization sends people to 3 separate surveys, the outcome
  # measure of meat selection appears in three separate columns, one for each
  # arm. Combine them.
  unite("meat_outcome", c(
    protein_1.factor,
    protein_2.factor,
    protein_3.factor), na.rm=TRUE, sep='') %>%
  # Same drill as above for block order
  unite("block_order", c(
    block_order_1,
    block_order_2,
    block_order_3), na.rm=TRUE, sep='') %>%
  mutate(meat_outcome=as_factor(meat_outcome),
         # The order of the survey blocks is reported in columns with labels
         # automatically generated by RedCap. The labels differ by arm of the
         # survey since each survey receives different labels 1-3. Remove these
         # labels since they aren't relevant to block order, then manually
         # recode the factors to use shorter, clearer names.
         block_order=as_factor(str_replace_all(block_order, "_1|_2|_3", "")),
         block_order=fct_recode(block_order,
                                'Pen-Shirt-Taco'='q_pen_instruct+pen_color+pen_tip+pen_paper-q_shirt_color+shirt_style+shirt_size+shirt_material-q_tacos+protein+tortilla+topp+addons+bev',
                                'Shirt-Taco-Pen'='q_shirt_color+shirt_style+shirt_size+shirt_material-q_tacos+protein+tortilla+topp+addons+bev-q_pen_instruct+pen_color+pen_tip+pen_paper',
                                'Pen-Taco-Shirt'='q_pen_instruct+pen_color+pen_tip+pen_paper-q_tacos+protein+tortilla+topp+addons+bev-q_shirt_color+shirt_style+shirt_size+shirt_material',
                                'Shirt-Pen-Taco'='q_shirt_color+shirt_style+shirt_size+shirt_material-q_pen_instruct+pen_color+pen_tip+pen_paper-q_tacos+protein+tortilla+topp+addons+bev',
                                'Taco-Pen-Shirt'='q_tacos+protein+tortilla+topp+addons+bev-q_pen_instruct+pen_color+pen_tip+pen_paper-q_shirt_color+shirt_style+shirt_size+shirt_material',
                                'Taco-Shirt-Pen'='q_tacos+protein+tortilla+topp+addons+bev-q_shirt_color+shirt_style+shirt_size+shirt_material-q_pen_instruct+pen_color+pen_tip+pen_paper')
         )

# Clean up various columns
label(data_clean$edu_v2_57dade.factor) = "Maximum education level achieved"
data_clean$edu_v2_57dade.factor = as.factor(data_clean$edu_v2_57dade.factor, ordered=TRUE)
label(data_clean$block_order) = "Order of Survey Blocks"

# Munge the labels from redcap: every categorical column is provided in two
# versions, say X and X.factor. The latter uses R's factor, but only the
# former actually has a label. We get the label from one and add it to the
# other.
for (col in colnames(data)){

  if (is.factor(data[[col]])){

    old_col = str_replace(col, '.factor', '')
    new_label = label(data[[old_col]])

    if (stringr::str_detect(new_label, "choice=")){
      new_label = str_extract(new_label, "(?<=choice=)[A-Za-z\ ]+")
    }

    label(data_clean[[col]]) = new_label
    }

  }

# Balance table and population characteristics
library(table1)

table1(~gender___1.factor + gender___2.factor + gender___99.factor + edu_v2_57dade.factor +
       eth_v2_a71477___1.factor + eth_v2_a71477___2.factor + eth_v2_a71477___3.factor +
       eth_v2_a71477___4.factor + eth_v2_a71477___5.factor + eth_v2_a71477___6.factor +
       eth_v2_a71477___7.factor + eth_v2_a71477___8.factor + eth_v2_a71477___9.factor + eth_v2_a71477___99.factor + polit_v2_d30881.factor + dob + state.factor | redcap_event_name.factor,
       data=data_clean)

# Order effects
table1(~data_clean$block_order)

# Demographic effects


# Attention check


# Awareness check
data_clean$q_awareness_bool = data_clean$q_awareness.factor == "Learning how plant-based protein options affect the foods people choose"
table1(~q_awareness_bool | redcap_event_name.factor, data_clean)

# Manipulation check


# Duration of survey
data$time_end2_v2_adfa0b

# Vegans and vegs
data$ffq_chk_v2_3d0d37.factor
data$ffq_cow_v2_0b5bcd.factor
data$ffq_dairy_v2_c6de32.factor
data$ffq_pig_v2_6469db.factor
data$ffq_fish_v2_29061b.factor
data$ffq_eggs_v2_27b663.factor
data$ffq_fish_v2_29061b.factor
data$ffq_pb_v2_b7a5db.factor

# Main outcome
## Descriptive
table1(~meat_outcome | redcap_event_name.factor, data_clean)

## Intervention effects


# Questions for Jessica
# - Where do Random, protein_1|_2|_3 come from?
# - Survey start time? Currently I have end time at data$time_end2_v2_adfa0b
# - [Check pre-reg] what are we doing with the county data? Same as EatingVeg?
# - Possible to fix the naming of Arms (redcap_event_name); I can fix ofc, but it introduces the opportunity for errror.
# - Some awareness checks are missing (q_awareness): is this question not mandatory?