library(DeclareDesign)
library(table1)
library(tidyverse)

##################################
# Data downloading and ingestion #
##################################
# The 0_data_ingestion.r script is automatically generated by RedCap
# To Download the newest data
# 1. Go to https://redcap.stanford.edu/redcap_v14.7.5/DataExport/index.php?pid=30009
# 2. In Row A, click 'Export All Data'
# 3. Select 'R Statistical Software' as the export format.
# 4. Check 'Export survey identifier field and survey timestamp field(s)?', but
#    no other check boxes.

source("0_data_ingestion.R")
source("1_power_analysis.R")

###########################
# Pre-cleaning validation #
###########################
# Check, that there's exactly one outcome measure response in each row; should
# return TRUE
all(rowSums(is.na(data[c("protein_1.factor", "protein_2.factor", "protein_3.factor")])) == 2)


#################
# Data cleaning #
#################
# Munge the labels from redcap: every categorical column is provided in two
# versions, say X and X.factor. The latter uses R's factor, but only the
# former actually has a label. We get the label from one and add it to the
# other.
for (col in colnames(data)){

  if (is.factor(data[[col]])){

    old_col = str_replace(col, '.factor', '')
    new_label = label(data[[old_col]])

    if (stringr::str_detect(new_label, "choice=")){
      new_label = str_extract(new_label, "(?<=choice=)[A-Za-z\ ]+")
    }

    print(c(col, old_col, new_label))
    label(data[[col]]) = new_label
  }

}

data_clean = data %>%
  # Filter out consent form signature events
  dplyr::filter(!stringr::str_detect(redcap_event_name, "^consent")) %>%

  # Since RedCap randomization sends people to 3 separate surveys, the outcome
  # measure of meat selection appears in three separate columns, one for each
  # arm. Combine them.
  unite("meat_outcome", c(
    protein_1.factor,
    protein_2.factor,
    protein_3.factor), na.rm=TRUE, sep='') %>%

  # Same drill as above for block order
  unite("block_order", c(
    block_order_1,
    block_order_2,
    block_order_3), na.rm=TRUE, sep='') %>%

  unite("manipulation_check", c(
    aware_carn_v2.factor,
    aware_stk_v2.factor,
    aware_chicknitas_v2.factor,
    aware_veg_v2.factor,
    aware_sofr_v2.factor,
    aware_chicken_v2.factor,
    aware_barba_v2.factor
    ), na.rm=TRUE, sep='') %>%

  mutate(
         # The order of the survey blocks is reported in columns with labels
         # automatically generated by RedCap. The labels differ by arm of the
         # survey since each survey receives different labels 1-3. Remove these
         # labels since they aren't relevant to block order, then manually
         # recode the factors to use shorter, clearer names.
         block_order=as_factor(str_replace_all(block_order, "_1|_2|_3", "")),
         block_order=fct_recode(block_order,
          'Pen-Shirt-Taco'='q_pen_instruct+pen_color+pen_tip+pen_paper-q_shirt_color+shirt_style+shirt_size+shirt_material-q_tacos+protein+tortilla+topp+addons+bev',
          'Shirt-Taco-Pen'='q_shirt_color+shirt_style+shirt_size+shirt_material-q_tacos+protein+tortilla+topp+addons+bev-q_pen_instruct+pen_color+pen_tip+pen_paper',
          'Pen-Taco-Shirt'='q_pen_instruct+pen_color+pen_tip+pen_paper-q_tacos+protein+tortilla+topp+addons+bev-q_shirt_color+shirt_style+shirt_size+shirt_material',
          'Shirt-Pen-Taco'='q_shirt_color+shirt_style+shirt_size+shirt_material-q_pen_instruct+pen_color+pen_tip+pen_paper-q_tacos+protein+tortilla+topp+addons+bev',
          'Taco-Pen-Shirt'='q_tacos+protein+tortilla+topp+addons+bev-q_pen_instruct+pen_color+pen_tip+pen_paper-q_shirt_color+shirt_style+shirt_size+shirt_material',
'Taco-Shirt-Pen'='q_tacos+protein+tortilla+topp+addons+bev-q_shirt_color+shirt_style+shirt_size+shirt_material-q_pen_instruct+pen_color+pen_tip+pen_paper'),

         # For analysis, we actually only care about the effects of block order
         # on the taco purchasing task. Thus, we can ignore the order of blocks
         # after the tacos.
         block_order_pre_tacos=str_replace_all(block_order, "-?Taco.*", ""),
         block_order_pre_tacos=fct_recode(block_order_pre_tacos,
                                          'No Task'=''),

         manipulation_check=factor(manipulation_check),

         arm=factor(fct_recode(redcap_event_name.factor,
                    '1 Veg Option'="August 2024 (Arm 5: Group A)",
                    '2 Veg Options'="August 2024 (Arm 2: Arm 2)",
                    '3 Veg Options'="August 2024 (Arm 3: Arm 3)"),
                    ordered=TRUE,
                    levels=c('1 Veg Option',
                             '2 Veg Options',
                             '3 Veg Options')
         ),

         meat_outcome=factor(meat_outcome,
                             # Note we manually copy over levels, which were
                             # lost in the `unite` function
                             levels=levels(data$protein_3.factor)),

         # Represent the filling choice as two categories: meat or not meat
         meat_outcome_2_cat=fct_collapse(
           meat_outcome,
           Yes=c(
             'STEAK',
             'CHICKEN',
             'CARNITAS',
             'BEEF BARBACOA'),
           No=c(
             'VEGGIE Includes Guacamole',
             'I would not order any of these fillings.',
             'SOFRITAS Plant-Based Protein'
             )
           ),

        # Encode those categories numerically
        meat_outcome_binary=as.numeric(meat_outcome_2_cat) - 1,

        meat_outcome_chicken_binary = fct_collapse(
          meat_outcome,
          Chicken=c('CHICKEN'),
          'Not Chicken'=c(
            'VEGGIE Includes Guacamole',
            'I would not order any of these fillings.',
            'SOFRITAS Plant-Based Protein',
            'STEAK',
            'CARNITAS',
            'BEEF BARBACOA')
        ),
        meat_outcome_chicken_binary=as.numeric(meat_outcome_chicken_binary) - 1,

        meat_outcome_not_chicken_binary = fct_collapse(
          meat_outcome,
          'Meat not chicken'=c(
            'STEAK',
            'CARNITAS',
            'BEEF BARBACOA'),
          'Other'=c(
            'CHICKEN',
            'VEGGIE Includes Guacamole',
            'I would not order any of these fillings.',
            'SOFRITAS Plant-Based Protein')
        ),
        meat_outcome_not_chicken_binary=as.numeric(meat_outcome_not_chicken_binary) - 1

  ) # End of data cleaning pipe

# Manually label and cast to ordered factors
label(data_clean$edu_v2_57dade.factor) = "Maximum education level achieved"
data_clean$edu_v2_57dade.factor = factor(data_clean$edu_v2_57dade.factor, ordered=TRUE)
label(data_clean$block_order) = "Order of Tasks"
label(data_clean$block_order_pre_tacos) = "Order of Tasks Prior to Taco Selection"
label(data_clean$meat_outcome_2_cat) = "Selected a meat filing?"


############################
# Post-cleaning validation #
############################
# TODO Check that chicin'tas is ordered in Arm 3 only, Sofritas only in Arm 2 and 3


####################
# Quality controls #
####################
# Balance: Did randomization succeed? Table of demographic characteristics.
table1(~gender___1.factor + gender___2.factor + gender___99.factor + edu_v2_57dade.factor +
  eth_v2_a71477___1.factor + eth_v2_a71477___2.factor + eth_v2_a71477___3.factor +
  eth_v2_a71477___4.factor + eth_v2_a71477___5.factor + eth_v2_a71477___6.factor +
  eth_v2_a71477___7.factor + eth_v2_a71477___8.factor + eth_v2_a71477___9.factor +
  eth_v2_a71477___99.factor + polit_v2_d30881.factor + dob + state.factor | arm,
  data=data_clean)

# Order effects: Did the decoy tasks effect taco selection?
table1(~data_clean$block_order_pre_tacos)
lm_robust(meat_outcome_binary ~ block_order_pre_tacos + arm, data_clean, se_type='HC0')

# Attention check: Did participants pass the attention checks?
# TODO

# Awareness check: Were participant aware of the study's purpose?
data_clean$q_awareness_bool = data_clean$q_awareness.factor == "Learning how plant-based protein options affect the foods people choose"
label(data_clean$q_awareness_bool) = "Aware of Study Purpose"
table1(~q_awareness_bool | arm, data_clean)

# Manipulation check: Did participants recall what taco filling they ordered?
data_clean$manipulation_check_bool = str_replace(
  str_replace(data_clean$manipulation_check, "^No.*", "No"), "^Yes.*", "Yes")
data_clean$manipulation_check_bool = na_if(data_clean$manipulation_check_bool, "")
label(data_clean$manipulation_check_bool) = "Successfully recalled taco order?"
table1(~manipulation_check_bool, data_clean)

# Straight-lining: For the food frequency questions, was there any evidence of
# respondents simply checking the same answer each time in the grid response?
# TODO

# Speeding: How quickly did participant complete the survey?
# TODO
data$time_end2_v2_adfa0b


#####################################
# Confirmatory inferential analyses #
#####################################
# Hypothesis 1: Increasing vegan option availability will decrease meat demand.

table1(~meat_outcome | arm, data_clean)
table1(~meat_outcome_2_cat | arm, data_clean)

# TODO XXX Note this provides a quadratic term for `arm` by default since it
# an ordered categorical. I suspect this should likely be turned off.
lm_robust(meat_outcome_binary ~ arm, data_clean, se_type='HC0')

# Hypothesis 2 Specificity: Availability of chicin'tas (plant-based chicken
# meat) will decrease chicken consumption more than it will decrease other meat
# consumption.
# TODO integrate with power analysis here

# Get data from just the two relevant arms
data_clean_h2 = data_clean %>%
  filter(arm %in% c('2 Veg Options', '3 Veg Options'))

H2_Specificity_CI_2(data_clean_h2, 50)

####################################
# Exploratory inferential analyses #
####################################
# Effect among Chipotle consumers: Sub-set analysis of main hypotheses among
# people who have eaten at Chipotle more than once in the past 3 months.
# TODO Describe Chipotle frequency, subset data, re-run confirmatory hypothesis
# tests.

# Change in Opt-In: Will adding more vegan options cause more people to opt-in
# to ordering a taco? For example, perhaps it will attract more vegans who would
# not have ordered otherwise.
# TODO

# Attentiveness effects:
# TODO

# Demographic effects: Probably need to dichotomize ethnicity, but may want to
# set a pre-registered criteria
# TODO XXX Below code does not run
# lm_robust(meat_outcome_binary ~ gender___1.factor + gender___2.factor +
#  gender___99.factor + edu_v2_57dade.factor +
#  eth_v2_a71477___1.factor + eth_v2_a71477___2.factor + eth_v2_a71477___3.factor +
#  eth_v2_a71477___4.factor + eth_v2_a71477___5.factor + eth_v2_a71477___6.factor +
#  eth_v2_a71477___7.factor + eth_v2_a71477___8.factor + eth_v2_a71477___9.factor +
#  eth_v2_a71477___99.factor + polit_v2_d30881.factor + dob + state.factor,
#  data_clean, se_type='HC0')

# Timezone effects: Since recruitment tends to be very rapid, participants in
# different time zones will vary in how close they are to a regular meal time.
# This can potentially be exploited estimate the effect of proximity to meal
# time.
# TODO

# Vegans and vegetarians: How did they respond to the intervention? What's
# their prevalence?
# TODO
data$ffq_chk_v2_3d0d37.factor
data$ffq_cow_v2_0b5bcd.factor
data$ffq_dairy_v2_c6de32.factor
data$ffq_pig_v2_6469db.factor
data$ffq_fish_v2_29061b.factor
data$ffq_eggs_v2_27b663.factor
data$ffq_fish_v2_29061b.factor
data$ffq_pb_v2_b7a5db.factor